language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
  - php: 5.4
    env: PHPCS=1 DEFAULT=0

  - php: 5.4
    env: COVERALLS=1 DEFAULT=0

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev

before_script:
  - sh -c "if [ '$PHPCS' = '1' ]; then composer require cakephp/cakephp-codesniffer:dev-master; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require --dev satooshi/php-coveralls:dev-master; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then mkdir -p build/logs; fi"
  - phpenv rehash

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit --stderr; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then ./vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then phpunit --stderr --coverage-clover build/logs/clover.xml; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then php vendor/bin/coveralls -c .coveralls.yml -v; fi"

notifications:
  email: false
